apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy
  labels:
    run: udagram-reverse-proxy
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: udagram-reverse-proxy